spring:
  profiles:
    active: test
  # Thymeleaf
  thymeleaf:
    cache: false

  #H2 Database
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

# My Own Configuration properties
tacos:
  orders:
    page-size: 5
  page-size: 2