spring:
  # Thymeleaf
  thymeleaf:
    cache: false

  #H2 Database
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
h2-server:
  port: 8081