spring:
  # Thymeleaf
  thymeleaf:
    cache: false

  #H2 Database
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

# Configuring the embedded server
server:
  port: 8443
  ssl:
    key-store: file:///home/nero/mykeys.jks
    key-store-password: phuongsover1
    key-password: phuongsover1

# My Own Configuration properties
tacos:
  orders:
    page-size: 5
  page-size: 2