spring:
  profiles:
    active: test,jms-listener
  # Thymeleaf
  thymeleaf:
    cache: false

  #H2 Database
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

  # Configuring spring rest data
  data:
    rest:
      base-path: /data-api

  # Configuring resources server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authserver:9000/oauth2/jwks
# Configuring the embedded server
server:
  port: 8080

# My Own Configuration properties
tacos:
  orders:
    page-size: 5
  page-size: 2